site_name: ArchGeo
site_url: https://www.huiwang.me/mkdocs-archgeo/
site_author: Hui Wang

# Repository
repo_name: wwmore/mkdocs-archgeo
repo_url: https://github.com/WWmore/mkdocs-archgeo

theme: 
  name: material
  custom_dir: material/overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.follow
    - toc.integrate

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: lime
      accent: deep purple
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: green
      accent: orange

plugins:
  - social

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/WWmore
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/HuiWang34957044

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/WWmore"  target="_blank" rel="noopener">Hui Wang</a>