site_name: ArchGeo
site_url: https://www.huiwang.me/mkdocs-archgeo/
site_author: Hui Wang

# Repository
repo_name: WWmore/DOS
repo_url: https://github.com/WWmore/DOS

theme: 
  name: material
  favicon: assets/AG.png
  logo: assets/gif_trans.gif
  icon:
    repo: fontawesome/brands/github-alt
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  features:
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - navigation.path
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.follow

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
      primary: cyan
      accent: deep purple
    - scheme: slate 
      toggle:
        icon: material/weather-night
        name: Switch to light mode    
      primary: teal
      accent: orange

plugins:
  - social
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [src, src/meshpy, src/quadrings]  # 指定源代码路径
        options:
          show_root_heading: false
          show_source: false
          docstring_style: "numpy"
  # - bibtex:
  #     bib_file: assets/refs.bib

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/WWmore
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/HuiWang34957044

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
copyright: |
  &copy; 2023 <a href="https://github.com/WWmore"  target="_blank" rel="noopener">Hui Wang</a>